In [4]:
import pandas as pd
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
#list('321') #Relembrando que esse comando irá criar uma lista com os números 3,2,1 em forma de string.
df = pd.DataFrame(data, list('321'), list('ZYX'))
df #As listas armazenadas na lista data tem o list('321') como index e o list('ZYX') nomeando cada coluna

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9

In [6]:
df.sort_index(inplace = True)
df #Aqui organizamos o index em ordem crescente

   Z  Y  X
1  7  8  9
2  4  5  6
3  1  2  3

In [7]:
df.sort_index(inplace = True, axis = 1)
df #Organizamos também as colunas em ordem alfabética

   X  Y  Z
1  9  8  7
2  6  5  4
3  3  2  1

In [8]:
df.sort_values(by = 'X', inplace = True)
df #Organizando a tabela colocando os valores da coluna X em ordem crescente

   X  Y  Z
3  3  2  1
2  6  5  4
1  9  8  7

In [9]:
df.sort_values(by = ['X','Y'], inplace = True)
df #Organizando a tabela colocando os valores da coluna X e Y em ordem crescente

   X  Y  Z
3  3  2  1
2  6  5  4
1  9  8  7

In [10]:
df.sort_values(by = '3', axis = 1, inplace = True)
df #Organizando os valores do index 3 em ordem crescente.

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9